# Generated by Django 4.1.7 on 2023-05-02 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('heading0', models.CharField(max_length=50)),
                ('cheading0', models.CharField(max_length=500)),
                ('heading1', models.CharField(max_length=50)),
                ('cheading1', models.CharField(max_length=500)),
                ('sub_heading', models.CharField(max_length=50)),
                ('csub_heading', models.CharField(max_length=500)),
                ('pub_date', models.DateField(verbose_name=datetime.datetime(2023, 5, 2, 6, 4, 41, 704004))),
            ],
        ),
    ]
