# Generated by Django 4.1.7 on 2023-04-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default='', max_length=50)),
                ('phone', models.IntegerField(default='', max_length=10)),
                ('desc', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
