# Generated by Django 4.1.7 on 2023-04-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_jason', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default='', max_length=50)),
                ('phone', models.IntegerField(default='', max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=10)),
                ('zip_code', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
