# Generated by Django 4.1.7 on 2023-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('time_stamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.AddField(
            model_name='orders',
            name='State',
            field=models.CharField(default='', max_length=10),
        ),
    ]
