# Generated by Django 4.1.7 on 2023-05-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
