# Generated by Django 4.1.7 on 2023-05-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.CharField(default=' ', max_length=5000),
        ),
    ]
