# Generated by Django 4.1.7 on 2023-05-05 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0002_makeblog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeblog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
