# Generated by Django 4.1.7 on 2023-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0003_makeblog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeblog',
            name='cheading0',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='makeblog',
            name='cheading1',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='makeblog',
            name='csub_heading',
            field=models.CharField(max_length=5000),
        ),
    ]
