# Generated by Django 4.1.7 on 2023-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_alter_makeblog_cheading0_alter_makeblog_cheading1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeblog',
            name='image',
            field=models.ImageField(default='', upload_to='blog2/images'),
        ),
    ]
